package manager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import logindetails.loginpage;

/**
 *
 * @author 160571F
 */
public class AcceptLeaves extends javax.swing.JFrame {
    
    static AcceptLeaves al;
    final Connection c = loginpage.createLoginpage().getConnection();
    ResultSet s ;

    /**
     * Creates new form AcceptLeaves
     */
    
    public ResultSet getLeaves() {
    	if(loginpage.getrole().equals("admin")) {
        	try {
        		PreparedStatement p = c.prepareStatement("select eid,leaveid,type,date,enddate,reason,status,name from (select eid,leaveid,type,date,enddate,reason,leavesubmissions.status from leavesubmissions left join employeedetails using(eid) where (supervisorid=? or supervisorid is null) and leavesubmissions.status='Pending') as t1 join employeepersonal using(eid)");
        		p.setString(1, loginpage.eid);
        		ResultSet s = p.executeQuery();

        		
        		return s;
        	} catch (SQLException e) {
        		JOptionPane.showMessageDialog(null, "No new Submissions");
				e.printStackTrace();
				return null;
			}
        }
    	else {
        	try {
        		PreparedStatement p = c.prepareStatement("select eid,leaveid,type,date,enddate,reason,status,name from (select eid,leaveid,type,date,enddate,reason,leavesubmissions.status from leavesubmissions left join employeedetails using(eid) where (supervisorid=?) and leavesubmissions.status='Pending') as t1 join employeepersonal using(eid)");
        		p.setString(1, loginpage.eid);
        		ResultSet s = p.executeQuery();

        		return s;
        	} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
				return null;
			}
    	}

    }
    public AcceptLeaves() {
        initComponents();
        	s= getLeaves();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        id = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        reason = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        StartDate = new javax.swing.JLabel();
        EndDate = new javax.swing.JLabel();
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s = getLeaves();
                try {
                	
					s.next();
					id.setText(s.getString(1));
					name.setText(s.getString(7));
					type.setText(s.getString(3));
					reason.setText(s.getString(6));
					StartDate.setText(s.getString(4));
					EndDate.setText(s.getString(5));
				} catch (SQLException e) {
					JOptionPane.showMessageDialog(null, "End of list");
				}
            }
        });

        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                	
					s.next();
					id.setText(s.getString(1));
					name.setText(s.getString(7));
					type.setText(s.getString(3));
					reason.setText(s.getString(6));
					StartDate.setText(s.getString(4));
					EndDate.setText(s.getString(5));
				} catch (SQLException e) {
					JOptionPane.showMessageDialog(null, "End of list");
				}
                
            }
        });

        id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        id.setText("ID");

        name.setText("Name");

        type.setText("Type");

        reason.setText("Reason");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Reject");
        
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	try {
					PreparedStatement s1 = c.prepareStatement("update leavesubmissions set status='Rejected' where leaveid=?");
					s1.setString(1, s.getString(2));
					s1.executeUpdate();
					s1.close();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
        
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	try {
					PreparedStatement s1 = c.prepareStatement("update leavesubmissions set status='Accepted' where leaveid=?");
					s1.setString(1, s.getString(2));
					s1.executeUpdate();
					s1.close();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Accept");

        StartDate.setText("Start Date");

        EndDate.setText("End Date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(42, 42, 42)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(45, 45, 45)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id)
                            .addComponent(name)
                            .addComponent(type)
                            .addComponent(reason)
                            .addComponent(StartDate)
                            .addComponent(EndDate))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(id)
                .addGap(18, 18, 18)
                .addComponent(name)
                .addGap(18, 18, 18)
                .addComponent(StartDate)
                .addGap(18, 18, 18)
                .addComponent(EndDate)
                .addGap(19, 19, 19)
                .addComponent(type)
                .addGap(18, 18, 18)
                .addComponent(reason)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {        
        al=new AcceptLeaves();   
        al.setTitle("Accept/Reject Leaves");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        al.setLocation(dim.width/2-al.getSize().width/2, dim.height/2-al.getSize().height/2);
        al.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EndDate;
    private javax.swing.JLabel StartDate;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel reason;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
